
envCheck: env.sh
	./env.sh

nodejs:
	echo "Language: NodeJS"; echo
	node physics.js; echo; echo;

python3:
	echo "Language: Python3"; echo
	python3 physics.py; echo; echo

erlang:
	echo "Language: erlang"
	echo
	erl physics.erl
	echo

all: envCheck nodejs python3