build1:
	clang-3.8 -lm  -Wformat=0  -o b.out  assignment_5_1_D0565617.c

test1: build1
	./b.out < hexadecimal_addition.txt

build2:
	clang-3.8 -lm  -Wformat=0  -o c.out  assignment_5_2_D0565617.c

test2: build2
	./c.out < hexadecimal_multiplication.txt
