
build:
	${CC} assignment_1_D0565617.c -o main ${CFLAGS};

test: test1 test2

test1:
	#
	# ========================
	# Start to test first file
	# ========================
	#
	#
	./main  < MacAuthr_prayer.txt

test2:
	#
	# =========================
	# Start to test second file
	# =========================
	#
	#
	./main  < Magic_Gift.txt 

clean:
	rm -f main
